[package]
name = "rbtc"
version = "0.1.0"
authors = ["Luca Lacerda <lucalacerda1@gmail.com>"]
edition = "2018"
repository = "https://github.com/lucawen/rbtc"

[dependencies]
reqwest = "0.9.12"
serde_derive = "1.0.89"
serde = "1.0.89"
serde_json = "1.0.39"
structopt = "0.2.15"
